using SmokeQuit.Services.LocDPX;
using SmokeQuit.SoapAPIServices.LocDPX.SoapModels;
using System.ServiceModel;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace SmokeQuit.SoapAPIServices.LocDPX.SoapServices
{
    [ServiceContract]
    public interface IChatsLocDpxSoapService
    {
        [OperationContract]
        Task<List<ChatsLocDpx>> GetAllAsync();
        [OperationContract]
        Task<ChatsLocDpx> GetByIdAsync(int chatId);
        [OperationContract]
        Task<int> CreateAsync(ChatsLocDpx chat);
        [OperationContract]
        Task<ChatsLocDpx> UpdateAsync(ChatsLocDpx chat);
        [OperationContract]
        Task<int> DeleteAsync(int chatId);
    }
    public class ChatsLocDpxSoapService : IChatsLocDpxSoapService
    {
        private readonly IServiceProviders _serviceProviders;

        public ChatsLocDpxSoapService(IServiceProviders serviceProviders)
        {
            _serviceProviders = serviceProviders ?? throw new ArgumentNullException(nameof(serviceProviders));
        }

        public async Task<int> CreateAsync(ChatsLocDpx chat)
        {
            try
            {
                // Validate required fields
                if (chat.UserId <= 0)
                {
                    Console.WriteLine("Invalid UserId: must be greater than 0");
                    return 0;
                }

                if (chat.CoachId <= 0)
                {
                    Console.WriteLine("Invalid CoachId: must be greater than 0");
                    return 0;
                }

                if (string.IsNullOrWhiteSpace(chat.Message))
                {
                    Console.WriteLine("Message cannot be empty");
                    return 0;
                }

                if (string.IsNullOrWhiteSpace(chat.SentBy))
                {
                    Console.WriteLine("SentBy cannot be empty");
                    return 0;
                }

                if (string.IsNullOrWhiteSpace(chat.MessageType))
                {
                    Console.WriteLine("MessageType cannot be empty");
                    return 0;
                }

                // Manual mapping from SOAP model to Repository model
                var repoChat = new SmokeQuit.Repository.LocDPX.Models.ChatsLocDpx
                {
                    // ✅ DON'T set ChatsLocDpxid - let the database handle it
                    // ChatsLocDpxid = 0, // This will be auto-generated by the database
                    UserId = chat.UserId,
                    CoachId = chat.CoachId,
                    Message = chat.Message.Trim(),
                    SentBy = chat.SentBy.Trim(),
                    MessageType = chat.MessageType.Trim(),
                    IsRead = chat.IsRead,
                    AttachmentUrl = string.IsNullOrWhiteSpace(chat.AttachmentUrl) ? null : chat.AttachmentUrl.Trim(),
                    ResponseTime = chat.ResponseTime,
                    CreatedAt = DateTime.Now // ✅ Always set to current time for new records
                };

                Console.WriteLine($"SOAP: Creating chat for UserId: {repoChat.UserId}, CoachId: {repoChat.CoachId}");

                var result = await _serviceProviders.ChatsService.CreateAsync(repoChat);

                Console.WriteLine($"SOAP: Chat creation result: {result}");
                return result;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error in SOAP CreateAsync: {ex.Message}");
                if (ex.InnerException != null)
                {
                    Console.WriteLine($"Inner Exception: {ex.InnerException.Message}");
                }
                return 0;
            }
        }

        public async Task<int> DeleteAsync(int chatId)
        {
            try
            {
                var result = await _serviceProviders.ChatsService.DeleteAsync(chatId);
                return result ? 1 : 0;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error in DeleteAsync: {ex.Message}");
                return 0;
            }
        }

        public async Task<List<ChatsLocDpx>> GetAllAsync()
        {
            try
            {
                // Get data from service
                var chats = await _serviceProviders.ChatsService.SearchAsync(null, null, null);

                // Manual mapping to avoid circular reference issues
                var result = chats.Select(chat => new ChatsLocDpx
                {
                    ChatsLocDpxid = chat.ChatsLocDpxid,
                    UserId = chat.UserId,
                    CoachId = chat.CoachId,
                    Message = chat.Message,
                    SentBy = chat.SentBy,
                    MessageType = chat.MessageType,
                    IsRead = chat.IsRead,
                    AttachmentUrl = chat.AttachmentUrl,
                    ResponseTime = chat.ResponseTime,
                    CreatedAt = chat.CreatedAt
                    // Don't include Coach and User navigation properties
                }).ToList();

                return result;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error in GetAllAsync: {ex.Message}");
                return new List<ChatsLocDpx>();
            }
        }

        public async Task<ChatsLocDpx> GetByIdAsync(int chatId)
        {
            try
            {
                var chat = await _serviceProviders.ChatsService.GetGetByIdAsync(chatId);

                if (chat == null)
                    return new ChatsLocDpx();

                var result = new ChatsLocDpx
                {
                    ChatsLocDpxid = chat.ChatsLocDpxid,
                    UserId = chat.UserId,
                    CoachId = chat.CoachId,
                    Message = chat.Message,
                    SentBy = chat.SentBy,
                    MessageType = chat.MessageType,
                    IsRead = chat.IsRead,
                    AttachmentUrl = chat.AttachmentUrl,
                    ResponseTime = chat.ResponseTime,
                    CreatedAt = chat.CreatedAt
                };

                return result;
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error in GetByIdAsync: {ex.Message}");
                return new ChatsLocDpx();
            }
        }

        public async Task<ChatsLocDpx> UpdateAsync(ChatsLocDpx chat)
        {
            try
            {
                // Manual mapping from SOAP model to Repository model
                var repoChat = new SmokeQuit.Repository.LocDPX.Models.ChatsLocDpx
                {
                    ChatsLocDpxid = chat.ChatsLocDpxid,
                    UserId = chat.UserId,
                    CoachId = chat.CoachId,
                    Message = chat.Message,
                    SentBy = chat.SentBy,
                    MessageType = chat.MessageType,
                    IsRead = chat.IsRead,
                    AttachmentUrl = chat.AttachmentUrl,
                    ResponseTime = chat.ResponseTime,
                    CreatedAt = chat.CreatedAt
                };

                var result = await _serviceProviders.ChatsService.UpdateAsync(repoChat);

                if (result > 0)
                {
                    // Return updated chat
                    return await GetByIdAsync(chat.ChatsLocDpxid);
                }

                return new ChatsLocDpx();
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error in UpdateAsync: {ex.Message}");
                return new ChatsLocDpx();
            }
        }
    }
}